### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by janmuennich** [nextcloud/llm2#16]
Apparently GPU support has been removed again recently. There are still the inactive feature branches `gpu-support` and `nvidia-support` but commit 4a1ccd1 removed it from `main`.

I cannot find any information though about the reasons behind this. Could the developers clarify the issue, if this is still on the roadmap and if and what help you would need?

**Comment by marcelklehr** [comment]
Hi @janmuennich
Yes, we're about to add GPU support again. ETA is some time next week.

**Comment by marcelklehr** [comment]
v1.2.0 is out now with NVIDIA GPU support
