### ISSUE TITLE
llm2 does not work in CPU only mode

### ISSUE THREAD

**Issue by suitcaseTrousers** [nextcloud/llm2#21]
Hey everyone,

I have a home server without an Nvidia GPU. Running something like Llama 3 8B would work on CPU only. However everytime Nextcloud sends a request to the llm2 docker container I get the following error:

`LanguageModel call using provider Local Large language Model: Meta-Llama-3-8B-Instruct.Q4_K_M failed: Text task returned error: llm2:llm2:Meta-Llama-3-8B-Instruct.Q4_K_M:free_prompt:free_prompt. Error: ('Error: Failed to initialize the LLM model on both GPU and CPU.', "Failed to load shared library '/root/.cache/pypoetry/virtualenvs/llm2-9TtSrW0h-py3.10/lib/python3.10/site-packages/llama_cpp/libllama.so': libcuda.so.1: cannot open shared object file: No such file or directory")`

I run Nexctloud 29.0.4, AppApi 3.0.0 and I have configured the docker socket proxy to run in CPU mode.

I understand that the Gitlab Readme states that Nvidia drivers are required to run the container, but shouldn't the fallback CPU only mode run nonetheless?

Any help on how to get the container to run in CPU only mode is greatly appreciated.

Cheers!

**Comment by suitcaseTrousers** [comment]
I forgot to add: I am running version 1.2.5 of llm2. Has this issue perhaps been addressed in version >2.0.0? 
Best

**Comment by kyteinsky** [comment]
should be fixed with the latest version.

**Comment by suitcaseTrousers** [comment]
Thanks, will try it once I upgraded to Nextcloud 30 :)

**Comment by thibaultmol** [comment]
it's a bit confusing @kyteinsky how the readme makes it seem like this intergration only works if you have a gpu on the system. but it works cpu only as well it seems? maybe the readme should reflect that

**Comment by suitcaseTrousers** [comment]
@kyteinsky I works with Nextcloud 30. Thank you!
