### ISSUE TITLE
Installation instructions 

### ISSUE THREAD

**Issue by Forza-tng** [nextcloud/llm2#7]
Hi,

How do you install llm2 with NC? I have NC28.0.4 and run Gentoo Linux.

**Comment by marcelklehr** [comment]
see https://docs.nextcloud.com/server/latest/admin_manual/ai/index.html

**Comment by Forza-tng** [comment]
Thanks. I was hoping to avoid the whole Docker thing, but I see is becoming a requirement for several apps now.

**Comment by marcelklehr** [comment]
Note, that you don't need to run nextcloud itself in docker to use External Apps. But yeah, docker allows us to do some stuff that would otherwise be very difficult
