### ISSUE TITLE
The app not shown on the External App list in Nextcloud

### ISSUE THREAD

**Issue by MELVARDEV** [nextcloud/llm2#8]
Hi, I can't figure out how to install this. The app doesn't show up among other External Apps to install. 
Here is the response of the available External Apps that I see available on my NextCloud instance. I'm not sure if the problem is on my end or perhaps I don't understand something.
![image](https://github.com/nextcloud/llm2/assets/36396619/4523080c-18f6-42f0-82ac-abec523f437a)

**Comment by marcelklehr** [comment]
cc @bigcat88 @andrey18106

**Comment by andrey18106** [comment]
@MELVARDEV Hi!

What version of Nextcloud are you using? You might not be in the supported NC versions range for that app so that it's not in the list.

**Comment by bigcat88** [comment]
please wait 1 day, tomorrow we will publish fix fir that

**Comment by MELVARDEV** [comment]
> @MELVARDEV Hi!
> 
> What version of Nextcloud are you using? You might not be in the supported NC versions range for that app so that it's not in the list.



> please wait 1 day, tomorrow we will publish fix for that

Well you're completely right, I'm on 28.0.4 so I assumed the app is supported on this version. Thanks a lot for clarification

**Comment by marcelklehr** [comment]
@bigcat88 Wondering if we can support 28 as well with this app ... :thinking:

**Comment by andrey18106** [comment]
We can support only if the server repo backports the TextProcessing API changes to the stable28.

**Comment by marcelklehr** [comment]
Which changes were those again?

**Comment by andrey18106** [comment]
To use `getId()` as another unique identifier of provider interface along with original one based only on provider `::class`
